echo "REACT_APP_AWS_ACCESS_ID=${REACT_APP_AWS_ACCESS_ID}" >> './.env'
echo "REACT_APP_AWS_SECRET_KEY=${REACT_APP_AWS_SECRET_KEY}" >> './.env'
echo "REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}" >> './.env'
echo "REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}" >> './.env'

