version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Make script executable
                command: |
                  chmod 777 ./buildEnv.sh
            - run: 
                name: Build an environment file
                command: |
                  npm run buildEnv
            - run: 
                name: Install dependencies
                command: |
                  npm install
            - run: 
                name: Run tests
                command: |
                  npm test
            - run: 
                name: Deploy to s3 bucket
                command: |
                  npm run deploy
workflows:
    build-and-test:
      jobs:
        - build-and-test