version: 2.1
orbs:
  node: circleci/node@4.5.0
jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          name: Build an environment file
          command: |
            chmod 777 ./buildEnv.sh
            echo 'export REACT_APP_AWS_ACCESS_ID=${REACT_APP_AWS_ACCESS_ID}' >> $BASH_ENV
            echo 'export REACT_APP_AWS_SECRET_KEY=${REACT_APP_AWS_SECRET_KEY}' >> $BASH_ENV
            npm run buildEnv
      - run:
          name: Install aws cli
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            aws --version
      - node/install-packages:
            cache-path: ~/project/node_modules
            override-ci-command: npm install
      - run:
          name: Deploy to s3 bucket
          command: |
            npm run deploy
      - run:
          name: Invalidate cloudfront caches
          command: |
            chmod 777 ./invalidateCloudfrontCaches.sh
            npm run invalidateCloudfrontCaches
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
